//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSkills2017.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> OnSystemTime { get; set; }
        public System.DateTime LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public Nullable<bool> Crashe { get; set; }
        public string CrasheReason { get; set; }
        public string Date
        {
            get
            {
                return LoginTime.Date.ToString("dd.MM.yyyy");
            }
        }

        public string LoginTimeStr
        {
            get
            {
                try
                {
                    return LoginTime.ToString("T");
                }
                catch
                {
                    return "";
                }
            }
        }

        public string LogoutTimeStr
        {
            get
            {
                try
                {
                    return ((DateTime)LogoutTime).ToString("T");
                }
                catch
                {
                    return "";
                }
            }
        }

        public string TimeSpent
        {
            get
            {
                TimeSpan timeSpan = new TimeSpan(0, 0, OnSystemTime ?? 0);
                return $"{timeSpan.Hours}:{timeSpan.Minutes}:{timeSpan.Seconds}";
            }
        }

        public virtual Users Users { get; set; }
    }
}
